# -*- coding: utf-8 -*-
"""text_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F46B_VBtYKzycPj5r5MjmeDRgFxB8GL2
"""

import numpy as np

import tensorflow as tf

import pickle

from tensorflow.keras.preprocessing.sequence import pad_sequences

from google.colab import drive

drive.mount('/content/gdrive')

model = tf.keras.models.load_model(
    "/content/gdrive/MyDrive/Emotion_Project/saved_models/gru_text_emotion_model.keras"
)

from tensorflow.keras.preprocessing.text import tokenizer_from_json

import json

with open(
    "/content/gdrive/MyDrive/Emotion_Project/saved_models/text_tokenizer.json"
) as f:

    data = json.load(f)

    tokenizer = tokenizer_from_json(data)

emotion_labels = [

    "angry",

    "disgust",

    "fear",

    "happy",

    "neutral",

    "sad",

    "surprise"
]

max_length = 50

def predict_emotion(text):

    sequence = tokenizer.texts_to_sequences(
        [text]
    )

    padded = pad_sequences(
        sequence,
        maxlen=max_length,
        padding='post'
    )

    prediction = model.predict(padded)

    predicted_class = np.argmax(prediction)

    emotion = emotion_labels[predicted_class]

    confidence = np.max(prediction)

    return emotion, confidence

test_sentences = [

    "back",

    "base",

    "bath",

    "bean",

    "chair",

    "date",

    "door",

    "duck",

    "juice",

    "kite",

    "mouse",

    "nurse",

    "page",

    "ring",

    "time",

    "watch",

    "yes",

    "book",

    "dog",

    "water"
]

for sentence in test_sentences:

    print("=" * 40)

    print("TEXT:")

    print(sentence)

    sequence = tokenizer.texts_to_sequences(
        [sentence]
    )

    padded = pad_sequences(
        sequence,
        maxlen=max_length,
        padding='post'
    )

    prediction = model.predict(padded)[0]

    predicted_class = np.argmax(prediction)

    predicted_emotion = emotion_labels[predicted_class]

    print("\nPREDICTED:")

    print(predicted_emotion)

    print("\nCONFIDENCE:")

    for index, probability in enumerate(prediction):

        print(
            emotion_labels[index],
            ":",
            round(probability * 100, 2),
            "%"
        )

    print("=" * 40)

    print()

text = "I am very happy today"

emotion, confidence = predict_emotion(text)

print("Predicted Emotion:", emotion)

print("Confidence:", confidence)

text = "I love my family"

emotion, confidence = predict_emotion(text)

print("Predicted Emotion:", emotion)

print("Confidence:", confidence)