# -*- coding: utf-8 -*-
"""speech_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tb0ZI6mXbIiTCps0o4Of6QWVVlrWKDUH
"""

from google.colab import drive

drive.mount('/content/gdrive')

import numpy as np

import librosa

import tensorflow as tf



model = tf.keras.models.load_model(
    "/content/gdrive/MyDrive/Emotion_Project/saved_models/speech_model_fixed.keras"
)



# Emotion labels

emotion_labels = [
    "angry",
    "disgust",
    "fear",
    "happy",
    "neutral",
    "pleasant_surprise",
    "sad"
]



# MFCC extraction

def extract_mfcc(audio_path):

    audio, sample_rate = librosa.load(
        audio_path,
        sr=22050
    )

    mfcc = librosa.feature.mfcc(
        y=audio,
        sr=sample_rate,
        n_mfcc=40
    )

    mfcc = mfcc.T

    max_pad_length = 130

    if mfcc.shape[0] < max_pad_length:

        pad_width = max_pad_length - mfcc.shape[0]

        mfcc = np.pad(
            mfcc,
            pad_width=((0, pad_width), (0, 0)),
            mode='constant'
        )

    else:

        mfcc = mfcc[:max_pad_length, :]

    return mfcc



# Prediction function

def predict_emotion(audio_path):

    mfcc = extract_mfcc(audio_path)

    mfcc = np.expand_dims(mfcc, axis=0)

    prediction = model.predict(mfcc)

    predicted_class = np.argmax(prediction)

    emotion = emotion_labels[predicted_class]

    confidence = np.max(prediction)

    return emotion, confidence



# Test sample

audio_path = "OAF_base_angry.wav"

emotion, confidence = predict_emotion(
    audio_path
)

print("Predicted Emotion:", emotion)

print("Confidence:", confidence)

audio_path = "OAF_back_happy.wav"

emotion, confidence = predict_emotion(
    audio_path
)

print("Predicted Emotion:", emotion)

print("Confidence:", confidence)

audio_path = "sample1.wav"

emotion, confidence = predict_emotion(
    audio_path
)

print("Predicted Emotion:", emotion)

print("Confidence:", confidence)

audio_path = "sample2.wav"

emotion, confidence = predict_emotion(
    audio_path
)

print("Predicted Emotion:", emotion)

print("Confidence:", confidence)

audio_path = "sample3.wav"

emotion, confidence = predict_emotion(
    audio_path
)

print("Predicted Emotion:", emotion)

print("Confidence:", confidence)

audio_path = "sample4.wav"

emotion, confidence = predict_emotion(
    audio_path
)

print("Predicted Emotion:", emotion)

print("Confidence:", confidence)