# -*- coding: utf-8 -*-
"""speech_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mOQkAc4Eyhk_rAV1xIIWLxny4dO2BYdK
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import numpy as np
import librosa
import librosa.display
import matplotlib.pyplot as plt

!pip install librosa tensorflow scikit-learn

import librosa
import os
import matplotlib.pyplot as plt
import numpy as np

audio_path = "/content/drive/MyDrive/Emotion_Project/datasets/TESS/TESS Toronto emotional speech set data"

import zipfile

zip_path = "/content/drive/MyDrive/Emotion_Project/datasets/TESS/archive.zip"

extract_path = "/content/drive/MyDrive/Emotion_Project/datasets/TESS"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Extraction completed!")

import os

print(os.listdir("/content/drive/MyDrive"))

print(os.listdir("/content/drive/MyDrive/Emotion_Project"))

print(os.listdir("/content/drive/MyDrive/Emotion_Project/datasets"))

print(os.listdir("/content/drive/MyDrive/Emotion_Project/datasets/TESS"))

audio_path = "/content/drive/MyDrive/Emotion_Project/datasets/TESS/TESS Toronto emotional speech set data"

import os

folders = os.listdir(audio_path)

print(folders[:10])

folder = folders[0]

folder_path = os.path.join(audio_path, folder)

files = os.listdir(folder_path)

print(files[:5])

import librosa

sample_file = files[0]

sample_path = os.path.join(folder_path, sample_file)

signal, sr = librosa.load(sample_path, sr=22050)

print("Sampling Rate:", sr)
print("Signal Shape:", signal.shape)

import matplotlib.pyplot as plt

plt.figure(figsize=(12,4))

plt.plot(signal)

plt.title("Audio Waveform")

plt.xlabel("Time")

plt.ylabel("Amplitude")

plt.show()

trimmed_signal, _ = librosa.effects.trim(signal)

print("Original Length:", len(signal))
print("Trimmed Length:", len(trimmed_signal))

plt.figure(figsize=(12,4))

plt.plot(trimmed_signal)

plt.title("Trimmed Audio")

plt.show()

normalized_signal = trimmed_signal / np.max(np.abs(trimmed_signal))

max_len = 3 * sr

print(max_len)

import numpy as np

if len(normalized_signal) < max_len:

    padded_signal = np.pad(
        normalized_signal,
        (0, max_len - len(normalized_signal))
    )

else:

    padded_signal = normalized_signal[:max_len]

print(len(padded_signal))

mfcc = librosa.feature.mfcc(
    y=padded_signal,
    sr=sr,
    n_mfcc=40
)

mfcc = mfcc.T

print(mfcc.shape)

import librosa.display

plt.figure(figsize=(10,4))

librosa.display.specshow(
    mfcc.T,
    x_axis='time'
)

plt.colorbar()

plt.title("MFCC Features")

plt.show()

"""Process Entire Dataset"""

X = []
y = []

emotions = os.listdir(audio_path)

print(emotions)

for emotion_folder in emotions:

    folder_path = os.path.join(audio_path, emotion_folder)

    audio_files = os.listdir(folder_path)

    for file in audio_files:

        file_path = os.path.join(folder_path, file)

        try:

            signal, sr = librosa.load(file_path, sr=22050)

            # Trim silence
            signal, _ = librosa.effects.trim(signal)

            # Normalize
            signal = signal / np.max(np.abs(signal))

            # Fixed length
            max_len = 3 * sr

            if len(signal) < max_len:

                signal = np.pad(
                    signal,
                    (0, max_len - len(signal))
                )

            else:

                signal = signal[:max_len]


            # MFCC extraction
            mfcc = librosa.feature.mfcc(
                y=signal,
                sr=sr,
                n_mfcc=40
            )

            mfcc = mfcc.T


            # Store features
            X.append(mfcc)


            # Extract label
            label = emotion_folder.split('_')[1]

            y.append(label)

        except Exception as e:

            print("Error processing:", file)
            print(e)

X = np.array(X)

y = np.array(y)

print(X.shape)
print(y.shape)

np.save(
    "/content/drive/MyDrive/Emotion_Project/saved_models/X_speech.npy",
    X
)

np.save(
    "/content/drive/MyDrive/Emotion_Project/saved_models/y_speech.npy",
    y
)