# -*- coding: utf-8 -*-
"""speech_train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HAKFd-EOfi_033ac2C3J-r-zwpN5nnTw
"""

import matplotlib.pyplot as plt

import os
import numpy as np
import pandas as pd
import librosa

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Conv1D,
    MaxPooling1D,
    BatchNormalization,
    Bidirectional,
    LSTM,
    Dense,
    Dropout
)

from tensorflow.keras.callbacks import EarlyStopping

from google.colab import drive

drive.mount('/content/gdrive')

dataset_path = "/content/gdrive/MyDrive/Emotion_Project/datasets/TESS/TESS Toronto emotional speech set data"

paths = []
emotions = []

for folder in os.listdir(dataset_path):

    folder_path = os.path.join(
        dataset_path,
        folder
    )

    if os.path.isdir(folder_path):

        for file in os.listdir(folder_path):

            if file.endswith(".wav"):

                file_path = os.path.join(
                    folder_path,
                    file
                )

                emotion = file.split("_")[-1]
                emotion = emotion.replace(".wav", "")

                paths.append(file_path)
                emotions.append(emotion)

df = pd.DataFrame({
    "path": paths,
    "emotion": emotions
})

print(df.head())

print(df['emotion'].value_counts())

os.listdir(dataset_path)

train_df, test_df = train_test_split(
    df,
    test_size=0.2,
    random_state=42,
    stratify=df['emotion']
)

train_df, val_df = train_test_split(
    train_df,
    test_size=0.2,
    random_state=42,
    stratify=train_df['emotion']
)

print("Train:", len(train_df))

print("Validation:", len(val_df))

print("Test:", len(test_df))

def extract_mfcc(file_path):

    signal, sr = librosa.load(
        file_path,
        sr=22050
    )

    mfcc = librosa.feature.mfcc(
        y=signal,
        sr=sr,
        n_mfcc=40
    )

    mfcc = mfcc.T

    max_pad_length = 130

    if mfcc.shape[0] < max_pad_length:

        pad_width = max_pad_length - mfcc.shape[0]

        mfcc = np.pad(
            mfcc,
            pad_width=((0, pad_width), (0, 0)),
            mode='constant'
        )

    else:

        mfcc = mfcc[:max_pad_length]

    return mfcc

X_train = []
y_train = []

for index, row in train_df.iterrows():

    mfcc = extract_mfcc(row['path'])

    X_train.append(mfcc)

    y_train.append(row['emotion'])

X_train = np.array(X_train)

y_train = np.array(y_train)

print(X_train.shape)

print(y_train.shape)

X_val = []

y_val = []

for index, row in val_df.iterrows():

    mfcc = extract_mfcc(row['path'])

    X_val.append(mfcc)

    y_val.append(row['emotion'])

X_val = np.array(X_val)

y_val = np.array(y_val)

X_test = []

y_test = []

for index, row in test_df.iterrows():

    mfcc = extract_mfcc(row['path'])

    X_test.append(mfcc)

    y_test.append(row['emotion'])

X_test = np.array(X_test)

y_test = np.array(y_test)

print(X_train.shape)

print(X_val.shape)

print(X_test.shape)

label_encoder = LabelEncoder()

y_train_encoded = label_encoder.fit_transform(
    y_train
)

y_val_encoded = label_encoder.transform(
    y_val
)

y_test_encoded = label_encoder.transform(
    y_test
)

print(label_encoder.classes_)

y_train_encoded = to_categorical(
    y_train_encoded
)

y_val_encoded = to_categorical(
    y_val_encoded
)

y_test_encoded = to_categorical(
    y_test_encoded
)

print(y_train_encoded.shape)

print(y_val_encoded.shape)

print(y_test_encoded.shape)

model = Sequential()

model.add(

    Conv1D(
        64,
        kernel_size=3,
        activation='relu',
        input_shape=(130, 40)
    )
)

model.add(
    MaxPooling1D(
        pool_size=2
    )
)

model.add(
    BatchNormalization()
)

model.add(

    Bidirectional(

        LSTM(
            64
        )
    )
)

model.add(
    Dropout(0.3)
)

model.add(
    Dense(
        64,
        activation='relu'
    )
)

model.add(
    Dropout(0.3)
)

model.add(
    Dense(
        7,
        activation='softmax'
    )
)

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

early_stopping = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

history = model.fit(

    X_train,
    y_train_encoded,

    validation_data=(
        X_val,
        y_val_encoded
    ),

    epochs=30,

    batch_size=32,

    callbacks=[early_stopping]
)

test_loss, test_accuracy = model.evaluate(
    X_test,
    y_test_encoded
)

print("Test Accuracy:", test_accuracy)

"""1. ACCURACY GRAPH"""

plt.plot(
    history.history['accuracy'],
    label='Train Accuracy'
)

plt.plot(
    history.history['val_accuracy'],
    label='Validation Accuracy'
)

plt.xlabel('Epochs')

plt.ylabel('Accuracy')

plt.title('Speech Model Accuracy')

plt.legend()

plt.show()
plt.savefig(
    "/content/gdrive/MyDrive/Emotion_Project/results/speech_accuracy.png"
)

"""2. LOSS GRAPH"""

plt.plot(
    history.history['loss'],
    label='Train Loss'
)

plt.plot(
    history.history['val_loss'],
    label='Validation Loss'
)

plt.xlabel('Epochs')

plt.ylabel('Loss')

plt.title('Speech Model Loss')

plt.legend()

plt.savefig(
    "/content/gdrive/MyDrive/Emotion_Project/results/speech_loss.png"
)

plt.show()

"""3. CONFUSION MATRIX"""

y_pred = model.predict(X_test)

y_pred_classes = np.argmax(
    y_pred,
    axis=1
)

y_true = np.argmax(
    y_test_encoded,
    axis=1
)

from sklearn.metrics import confusion_matrix
import seaborn as sns

cm = confusion_matrix(
    y_true,
    y_pred_classes
)

plt.figure(figsize=(8,6))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.xlabel('Predicted')

plt.ylabel('Actual')

plt.title('Speech Emotion Confusion Matrix')

plt.savefig(
    "/content/gdrive/MyDrive/Emotion_Project/results/speech_confusion_matrix.png"
)

plt.show()

from sklearn.metrics import classification_report

print(
    classification_report(
        y_true,
        y_pred_classes,
        target_names=label_encoder.classes_
    )
)

model.save(
    "/content/gdrive/MyDrive/Emotion_Project/saved_models/speech_model_fixed.keras"
)